export const SET_USER = 'SET_USER'
export const SET_TOKEN = 'SET_TOKEN'
export const ADD_PLACE = 'ADD_PLACE'
export const SHOW_SNACKBAR = 'SHOW_SNACKBAR'
export const HIDE_SNACKBAR = 'HIDE_SNACKBAR'
export const SET_STRIPEKEY = 'SET_STRIPEKEY'
export const UPDATE_PLAN = 'UPDATE_PLAN'
